"""update tables

Revision ID: 4e8d5811ba3d
Revises: 3463b4482de7
Create Date: 2026-07-15 16:14:37.272413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8d5811ba3d'
down_revision: Union[str, None] = '3463b4482de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('checks', sa.Column('issues', sa.JSON(), nullable=False))
    op.add_column('checks', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('document_versions_document_id_fkey', 'document_versions', type_='foreignkey')
    op.create_foreign_key(None, 'document_versions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('size_kb', sa.Integer(), nullable=False))
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('documents_check_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'checks', ['check_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_check_id_fkey', 'documents', 'checks', ['check_id'], ['id'])
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('documents', 'size_kb')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.create_foreign_key('document_versions_document_id_fkey', 'document_versions', 'documents', ['document_id'], ['id'])
    op.drop_column('checks', 'checked_at')
    op.drop_column('checks', 'issues')
    op.drop_column('checks', 'reason')
    # ### end Alembic commands ###
